version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.2
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"

  redisdb:
    container_name: redisdb
    image: redis:6-alpine
    ports: 
      - "${REDIS_PORT}:6379"

  app:
    container_name: api_landing_page
    build: .
    command: yarn start
    depends_on:
      - mongodb
      - redisdb
    ports: 
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/app
